version: '3.8'
services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./monitoring:/app/monitoring
      - ./model:/app/model
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - '5000:5000'
    command: mlflow server --host 0.0.0.0 --port 5000